# Get the GCC preinstalled image from Docker Hub
FROM gcc:4.9

VOLUME /usr/src

# Specify the working directory
WORKDIR /usr/src

# Use GCC to compile the Test.cpp source file
#RUN g++ -o Test Test.cpp

# Run the program output from the previous step
CMD ["/bin/bash"]

